### ISSUE TITLE
Repository can't connect any more

### ISSUE THREAD

**Issue by sm02ll** [allejok96/repository.allejok96#2]
Repository can't connect any more.
Log show this message :
`Repository add-on repository.allejok96 uses old schema definition for the repository extension point! This is no longer supported, please update your addon to use <dir> definitions.`

Kodi's documentation explains this :
https://kodi.wiki/view/Add-on_repositories#Repository_Add-on

**Comment by sm02ll** [comment]
Attached zip works for me.
[repository.allejok96.zip](https://github.com/allejok96/repository.allejok96/files/10573195/repository.allejok96.zip)

**Comment by allejok96** [comment]
Thanks for the heads up and for taking time to make a working example! I'll fix it right away

**Comment by davidbenucci** [comment]
Thanks.

**Comment by allejok96** [comment]
Sorry for the delay, this was trickier than I thought. Probably everyone that has upgraded to Kodi 20 will have to download the zip manually once I push the fix... I'm doing some tests right now just to make sure I don't break it for Kodi 17 and 18.

**Comment by allejok96** [comment]
The update is out, and yep, those who upgraded to 20 already need to install the new repo zip.
